name: Deploy to Hostinger via FTP

on:
  push:
    branches:
      - master
      - main

jobs:
  web-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Código
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Instalar Dependências
      run: npm install

    - name: Compilar o Projeto (Build)
      run: npm run build

    - name: Enviar para Hostinger via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
